google:
  maps:
    key: AIzaSyBcnZSlI9Ct2OlQ0OfQW5cD9FfqTbCZCoE

server:
  contextPath: /api


spring:
    jackson:
        serialization:
            indent_output: true
            write-dates-as-timestamps: false
